### PR TITLE
 fix: build warnings and test failures (#3457)

### LINKED ISSUE #3457: Build Warnings and Test Failures (26.3.1)
`ArcadeDB Server v26.3.1-SNAPSHOT`

`Running on Mac OS X 15.7.3 - OpenJDK 64-Bit Server VM 25.0.2 (Homebrew)`

Build Warnings:

* ```
  [WARNING]  Parameter 'binaryMavenPlugins' is deprecated: Users should now use plugins instead. This option will be removed in v5.
  [WARNING] [DEPRECATED] The "binaryMavenPlugins" attribute is deprecated for removal in v5.0.0. Please replace
  <binaryMavenPlugins>
    <binaryMavenPlugin>
      ...
    </binaryMavenPlugin>
  </binaryMavenPlugins>
  ...with...
  <protocPlugins>
    <protocPlugin kind="binary-maven">
      ...
    </protocPlugin>
  </protocPlugins>
  moving forwards.
  ```

Test Failures:

* `engine`-module (MacOS only)
  ```
  [ERROR]   LSMVectorIndexConcurrentUpdateTest.concurrentInsertAndUpdateWithLSMVectorIndex:191 [No records should be corrupted before reopen] 
  expected: 0
   but was: 1
  ```
* `engine`-module (Linux only)
  ```
  [ERROR]   LSMTreeIndexTest.updateKeys:519 » Transaction Transaction error on commit
  ```
* `gremlin`-module (MacOS only)
  ```
  [ERROR]   GremlinMergeVConcurrentTest.concurrentMergeVWithThreadBucketStrategy:173 Test failed with 1 concurrent modification or other errors
  ```
* `e2e`-module (MacOS only)
  ```
  [ERROR]   JdbcQueriesTest » NoClassDefFound Could not initialize class com.arcadedb.e2e.ArcadeContainerTemplate
  [ERROR]   JsFunctionsTest.jsMathSum » NoClassDefFound Could not initialize class com.arcadedb.e2e.JsFunctionsTest
  [ERROR]   JsFunctionsTest.jsObjectComparison » NoClassDefFound Could not initialize class com.arcadedb.e2e.JsFunctionsTest
  [ERROR]   JsFunctionsTest.stringObjectAsInput » NoClassDefFound Could not initialize class com.arcadedb.e2e.ArcadeContainerTemplate
  [ERROR]   RemoteBoltDatabaseTest.connection » NoClassDefFound Could not initialize class com.arcadedb.e2e.RemoteBoltDatabaseTest
  [ERROR]   RemoteBoltDatabaseTest.parameterizedQuery » NoClassDefFound Could not initialize class com.arcadedb.e2e.RemoteBoltDatabaseTest
  [ERROR]   RemoteBoltDatabaseTest.queryBeerDatabase » NoClassDefFound Could not initialize class com.arcadedb.e2e.RemoteBoltDatabaseTest
  [ERROR]   RemoteBoltDatabaseTest.simpleReturnQuery » NoClassDefFound Could not initialize class com.arcadedb.e2e.ArcadeContainerTemplate
  [ERROR]   RemoteDatabaseJavaApiTest.backupDatabase » NoClassDefFound Could not initialize class com.arcadedb.e2e.RemoteDatabaseJavaApiTest
  [ERROR]   RemoteDatabaseJavaApiTest.createSchemaWithDynamicSqlScript » NoClassDefFound Could not initialize class com.arcadedb.e2e.RemoteDatabaseJavaApiTest
  [ERROR]   RemoteDatabaseJavaApiTest.createTypesAndDataWithSqlScripts » NoClassDefFound Could not initialize class com.arcadedb.e2e.RemoteDatabaseJavaApiTest
  [ERROR]   RemoteDatabaseJavaApiTest.createUnidirectionalEdge » NoClassDefFound Could not initialize class com.arcadedb.e2e.RemoteDatabaseJavaApiTest
  [ERROR]   RemoteDatabaseJavaApiTest.multipleInsert » NoClassDefFound Could not initialize class com.arcadedb.e2e.RemoteDatabaseJavaApiTest
  [ERROR]   RemoteDatabaseJavaApiTest.multipleInsertBatched » NoClassDefFound Could not initialize class com.arcadedb.e2e.RemoteDatabaseJavaApiTest
  [ERROR]   RemoteDatabaseJavaApiTest.multipleInsertSingleTransaction » NoClassDefFound Could not initialize class com.arcadedb.e2e.ArcadeContainerTemplate
  [ERROR]   RemoteDatabaseJavaApiTest.renameTypeAndAliases » NoClassDefFound Could not initialize class com.arcadedb.e2e.RemoteDatabaseJavaApiTest
  [ERROR]   RemoteDatabaseQueriesTest.simpleCypherQuery » NoClassDefFound Could not initialize class com.arcadedb.e2e.ArcadeContainerTemplate
  [ERROR]   RemoteDatabaseQueriesTest.simpleGremlinQuery » NoClassDefFound Could not initialize class com.arcadedb.e2e.RemoteDatabaseQueriesTest
  [ERROR]   RemoteDatabaseQueriesTest.simpleOpenCypherQuery » NoClassDefFound Could not initialize class com.arcadedb.e2e.RemoteDatabaseQueriesTest
  [ERROR]   RemoteDatabaseQueriesTest.simpleSQLQuery » NoClassDefFound Could not initialize class com.arcadedb.e2e.RemoteDatabaseQueriesTest
  [ERROR]   RemoteGrpcDatabaseTest.simpleCypherQuery » ExceptionInInitializer
  [ERROR]   RemoteGrpcDatabaseTest.simpleGremlinQuery » NoClassDefFound Could not initialize class com.arcadedb.e2e.RemoteGrpcDatabaseTest
  [ERROR]   RemoteGrpcDatabaseTest.simpleSQLQuery » NoClassDefFound Could not initialize class com.arcadedb.e2e.RemoteGrpcDatabaseTest
  ```
* `e2e`-module (Linux only)
  ```
  [ERROR]   RemoteBoltDatabaseTest.connection:60 » Client Protocol error, server suggested unexpected protocol version: 4.1
  [ERROR]   RemoteBoltDatabaseTest.parameterizedQuery:88 » Client Protocol error, server suggested unexpected protocol version: 4.1
  [ERROR]   RemoteBoltDatabaseTest.queryBeerDatabase:77 » Client Protocol error, server suggested unexpected protocol version: 4.1
  [ERROR]   RemoteBoltDatabaseTest.simpleReturnQuery:66 » Client Protocol error, server suggested unexpected protocol version: 4.1
  ```

### PR DESCRIPTION
**Pull request by robfrank**
- Add missing TYPE_BINARY -> byte[].class mapping in BinaryTypes.getClassFromType(), fixing BinaryIndexTest and LSMTreeIndexTest failures after database reopen
  - Fix LSMVectorIndex graph storage: create graphFile placeholder when no .vecgraph exists on disk, and reload graph as OnDiskGraphIndex after persistence so the current session benefits from inline vector storage immediately
  - Add explicit (String[]) null casts to resolve varargs compiler warnings in CheckDatabaseTest and RemoteDatabaseIT
  - Remove unused proto imports (empty.proto, struct.proto) from arcadedb-server.proto
  - Remove unused test-jar goal from e2e and e2e-perf modules
  - Add propertiesEncoding to maven-resources-plugin in root POM

### CODE REVIEW

File: engine/src/test/java/com/arcadedb/database/CheckDatabaseTest.java [hunk 1]
```diff
@@ -346,6 +346,6 @@ private int countEdgesSegmentList(final RID rootVertex) {
     final EdgeLinkedList outEdges = ((DatabaseInternal) database).getGraphEngine()
         .getEdgeHeadChunk((VertexInternal) rootVertex.asVertex(), Vertex.DIRECTION.OUT);
 
-    return (int) outEdges.count(null);
```
Comment (lvca) [inline engine/src/test/java/com/arcadedb/database/CheckDatabaseTest.java:349]: This should rather call count() without any arguments

File: server/src/test/java/com/arcadedb/remote/RemoteDatabaseIT.java [hunk 2]
```diff
@@ -238,17 +238,17 @@ void simpleTxGraph() throws Exception {
       final Vertex albert = connected.next();
       assertThat(albert.getString("lastName")).isEqualTo("Red");
 
-      assertThat(kimbal.countEdges(IN, null)).isEqualTo(1L);
+      assertThat(kimbal.countEdges(IN, (String[]) null)).isEqualTo(1L);
```
Comment (lvca) [inline server/src/test/java/com/arcadedb/remote/RemoteDatabaseIT.java]: same here, you can avoid passing params at all if null (vararg)

**Review by lvca — CHANGES_REQUESTED** [review]
